import Productwatch from "../../../../assets/Images/products/watch.webp";
export const featuredData = [
  {
    id: 1,
    image: Productwatch,
    brand: "Fantac",
    weight: "200g",
    delivary: "2-3 business days",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "Headphone",
    pName: "Smart headphone",
    ratings: 5,
    totalRatings: 120,
    price: 500,
    discount: 10,
    decription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 2,
    image: Productwatch,
    brand: "Apple",
    weight: "200g",
    delivary: "2-3 business days ",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "Phone",
    pName: "Smart Phone",
    ratings: 2.5,
    totalRatings: 90,
    price: 500,
    discount: 50,
    decription:
      "loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum ",
  },
  {
    id: 3,
    image: Productwatch,
    brand: "Oppo",
    weight: "200g",
    delivary: "2-3 business days ",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "Phone",
    pName: "Smart Phone",
    ratings: 4.5,
    totalRatings: 100,
    price: 500,
    discount: null,
    decription:
      "loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream ",
  },
  {
    id: 4,
    image: Productwatch,
    brand: "Ryzen",
    weight: "200g",
    delivary: "2-3 business days ",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "CPU",
    pName: "Ryzen 5 6670X",
    ratings: 0,
    totalRatings: 110,
    price: 400,
    discount: null,
    decription:
      "loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur ",
  },
  {
    id: 5,
    image: Productwatch,
    brand: "Microlab",
    weight: "200g",
    delivary: "2-3 business days ",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "Speaker",
    pName: "Smart Speaker",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
    decription:
      "loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream ",
  },
  {
    id: 6,
    image: Productwatch,
    brand: "Apple",
    weight: "200g",
    delivary: "2-3 business days ",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "Headphone",
    pName: "Smart Watch",
    ratings: 3.0,
    totalRatings: 110,
    price: 250,
    discount: 60,
    decription:
      "loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit",
  },
  {
    id: 7,
    image: Productwatch,
    brand: "Apple",
    weight: "200g",
    delivary: "2-3 business days ",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 3.5,
    totalRatings: 110,
    price: 350,
    discount: null,
    decription:
      "loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam",
  },
  {
    id: 8,
    image: Productwatch,
    brand: "Apple",
    weight: "200g",
    delivary: "2-3 business days ",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 5.0,
    totalRatings: 110,
    price: 300,
    discount: null,
    decription:
      "loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam",
  },
  {
    id: 9,
    image: Productwatch,
    brand: "Apple",
    weight: "200g",
    delivary: "2-3 business days ",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.5,
    totalRatings: 110,
    price: 550,
    discount: 20,
    decription:
      "loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam",
  },
  {
    id: 10,
    image: Productwatch,
    brand: "Apple",
    weight: "200g",
    delivary: "2-3 business days ",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 3.0,
    totalRatings: 110,
    price: 350,
    discount: null,
    decription:
      "loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam",
  },
  {
    id: 11,
    image: Productwatch,
    brand: "Apple",
    weight: "200g",
    delivary: "2-3 business days ",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.5,
    totalRatings: 110,
    price: 350,
    discount: 10,
    decription:
      "loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam",
  },
  {
    id: 12,
    image: Productwatch,
    brand: "Apple",
    weight: "200g",
    delivary: "2-3 business days ",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
    decription:
      "loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam",
  },
  {
    id: 13,
    image: Productwatch,
    brand: "Apple",
    weight: "200g",
    delivary: "2-3 business days ",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
    decription:
      "loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam",
  },
  {
    id: 14,
    image: Productwatch,
    brand: "Apple",
    weight: "200g",
    delivary: "2-3 business days ",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
    decription:
      "loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam",
  },
  {
    id: 15,
    image: Productwatch,
    brand: "Apple",
    weight: "200g",
    delivary: "2-3 business days ",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
    decription:
      "loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam",
  },
  {
    id: 16,
    image: Productwatch,
    brand: "Apple",
    weight: "200g",
    delivary: "2-3 business days ",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
    decription:
      "loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosamloream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam",
  },
  {
    id: 17,
    image: Productwatch,
    brand: "Apple",
    weight: "200g",
    delivary: "2-3 business days ",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
    decription:
      "loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam",
  },
  {
    id: 18,
    image: Productwatch,
    brand: "Apple",
    weight: "200g",
    delivary: "2-3 business days ",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
    decription:
      "loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam",
  },
  {
    id: 19,
    image: Productwatch,
    brand: "Apple",
    weight: "200g",
    delivary: "2-3 business days ",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
    decription:
      "loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam",
  },
  {
    id: 20,
    image: Productwatch,
    brand: "Apple",
    weight: "200g",
    delivary: "2-3 business days ",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
    decription:
      "loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam",
  },
  {
    id: 21,
    image: Productwatch,
    brand: "Apple",
    weight: "200g",
    delivary: "2-3 business days ",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
    decription:
      "loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam",
  },
  {
    id: 22,
    image: Productwatch,
    brand: "Apple",
    weight: "200g",
    delivary: "2-3 business days ",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
    decription:
      "loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam",
  },
  {
    id: 23,
    image: Productwatch,
    brand: "Apple",
    weight: "200g",
    delivary: "2-3 business days ",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
    decription:
      "loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam",
  },
  {
    id: 24,
    image: Productwatch,
    brand: "Apple",
    weight: "200g",
    delivary: "2-3 business days ",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
    decription:
      "loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam",
  },
  {
    id: 25,
    image: Productwatch,
    brand: "Apple",
    weight: "200g",
    delivary: "2-3 business days ",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
    decription:
      "loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam",
  },
  {
    id: 26,
    image: Productwatch,
    brand: "Apple",
    weight: "200g",
    delivary: "2-3 business days ",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
    decription:
      "loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam",
  },
  {
    id: 27,
    image: Productwatch,
    brand: "Microlab",
    weight: "200g",
    delivary: "2-3 business days ",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "Speaker",
    pName: "Smart speaker",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
    decription:
      "loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam",
  },
  {
    id: 28,
    image: Productwatch,
    brand: "Zotac",
    weight: "200g",
    delivary: "2-3 business days ",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "Graphics Card",
    pName: "Smart Watch",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
    decription:
      "loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam",
  },
  {
    id: 29,
    image: Productwatch,
    brand: "Nvidia",
    weight: "200g",
    delivary: "2-3 business days ",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "Graphics Card",
    pName: "Smart Watch",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
    decription:
      "loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam",
  },
  {
    id: 30,
    image: Productwatch,
    brand: "Blackberry",
    weight: "200g",
    delivary: "2-3 business days ",
    size: "XL",
    variant: ["Black", "White", "Blue", "Red"],
    pCategory: "Phone",
    pName: "Smart Phone",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
    decription:
      "loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam loream Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam voluptatum, Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam Lorem ipsum dolor sit amet consectetur adipisicing elit.laboriosam",
  },
];
