import Productwatch from "../../../../../src/assets/Images/products/watch.webp";
export const featuredData = [
  {
    id: 1,
    image: Productwatch,
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 5,
    totalRatings: 120,
    price: 500,
    discount: 10,
  },
  {
    id: 2,
    image: Productwatch,
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 2.5,
    totalRatings: 90,
    price: 500,
    discount: 50,
  },
  {
    id: 3,
    image: Productwatch,
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.5,
    totalRatings: 100,
    price: 500,
    discount: null,
  },
  {
    id: 4,
    image: Productwatch,
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 0,
    totalRatings: 110,
    price: 400,
    discount: null,
  },
  {
    id: 5,
    image: Productwatch,
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
  },
  {
    id: 6,
    image: Productwatch,
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 3.0,
    totalRatings: 110,
    price: 250,
    discount: 60,
  },
  {
    id: 7,
    image: Productwatch,
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 3.5,
    totalRatings: 110,
    price: 350,
    discount: null,
  },
  {
    id: 8,
    image: Productwatch,
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 5.0,
    totalRatings: 110,
    price: 300,
    discount: null,
  },
  {
    id: 9,
    image: Productwatch,
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.5,
    totalRatings: 110,
    price: 550,
    discount: 20,
  },
  {
    id: 10,
    image: Productwatch,
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 3.0,
    totalRatings: 110,
    price: 350,
    discount: null,
  },
  {
    id: 11,
    image: Productwatch,
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.5,
    totalRatings: 110,
    price: 350,
    discount: 10,
  },
  {
    id: 12,
    image: Productwatch,
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
  },
  {
    id: 13,
    image: Productwatch,
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
  },
  {
    id: 14,
    image: Productwatch,
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
  },
  {
    id: 15,
    image: Productwatch,
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
  },
  {
    id: 16,
    image: Productwatch,
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
  },
  {
    id: 17,
    image: Productwatch,
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
  },
  {
    id: 18,
    image: Productwatch,
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
  },
  {
    id: 19,
    image: Productwatch,
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
  },
  {
    id: 20,
    image: Productwatch,
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
  },
  {
    id: 21,
    image: Productwatch,
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.0,
    totalRatings: 110,
    price: 350,
    discount: null,
  },
];
