import Productwatch from "../../../../assets/Images/products/watch.webp";
export const SpringSaleData = [
  {
    id: 1,
    image: Productwatch,
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 5,
    totalRatings: 120,
    price: 500,
    discount: 10,
    stock: 1500,
    sold: 100,
  },
  {
    id: 2,
    image: Productwatch,
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 2.5,
    totalRatings: 90,
    price: 500,
    discount: 50,
    stock: 1000,
    sold: 500,
  },
  {
    id: 3,
    image: Productwatch,
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 4.5,
    totalRatings: 100,
    price: 500,
    discount: 30,
    stock: 100,
    sold: 50,
  },
  {
    id: 4,
    image: Productwatch,
    pCategory: "Watch",
    pName: "Smart Watch",
    ratings: 3.5,
    totalRatings: 110,
    price: 400,
    discount: 70,
    stock: 200,
    sold: 100,
  },
];
