import blogImage from "../../../../../src/assets/Images/Blog/blogimg.jpg";
export const TechTalksData = [
  {
    id: 1,
    image: blogImage,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    catagory: "Gadgets",
    postedBy: "faizan",
    date: "09/01/2025",
  },
  {
    id: 2,
    image: blogImage,
    title: "How to Choose the Right Laptop for Your Needs: Our Expert Says",
    catagory: "Tips",
    postedBy: "faizan",
    date: "05/01/2025",
  },
  {
    id: 3,
    image: blogImage,
    title: "High Quality vs Price: Why You Should Upgrade to A Smart TV?",
    catagory: "Review",
    postedBy: "ahmed",
    date: "17/01/2025",
  },
  {
    id: 4,
    image: blogImage,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    catagory: "Gadgets",
    postedBy: "danish",
    date: "01/01/2025",
  },
  {
    id: 5,
    image: blogImage,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    catagory: "tips",
    postedBy: "hasan",
    date: "01/01/2025",
  },
  {
    id: 6,
    image: blogImage,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    catagory: "Guide",
    postedBy: "rahul",
    date: "01/03/2025",
  },
  {
    id: 7,
    image: blogImage,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    catagory: "Guide",
    postedBy: "badshah",
    date: "11/03/2025",
  },
  {
    id: 8,
    image: blogImage,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    catagory: "Guide",
    postedBy: "calvin",
    date: "07/01/2025",
  },
  {
    id: 9,
    image: blogImage,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    catagory: "Guide",
    postedBy: "talha",
    date: "16/02/2025",
  },
  {
    id: 10,
    image: blogImage,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    catagory: "Guide",
    postedBy: "esha",
    date: "01/05/2025",
  },
  {
    id: 11,
    image: blogImage,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    catagory: "Guide",
    postedBy: "labib",
    date: "01/01/2025",
  },
  {
    id: 12,
    image: blogImage,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    catagory: "Guide",
    postedBy: "orko",
    date: "22/01/2025",
  },
  {
    id: 13,
    image: blogImage,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    catagory: "Guide",
    postedBy: "qasim",
    date: "03/01/2025",
  },
  {
    id: 14,
    image: blogImage,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    catagory: "Guide",
    postedBy: "khalid",
    date: "14/02/2025",
  },
  {
    id: 15,
    image: blogImage,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    catagory: "Guide",
    postedBy: "rushad",
    date: "18/11/2025",
  },
  {
    id: 16,
    image: blogImage,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    catagory: "Guide",
    postedBy: "waseem",
    date: "01/07/2025",
  },
  {
    id: 17,
    image: blogImage,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    catagory: "Guide",
    postedBy: "naveed",
    date: "21/01/2025",
  },
  {
    id: 18,
    image: blogImage,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    catagory: "Guide",
    postedBy: "ahmed",
    date: "01/03/2025",
  },
  {
    id: 19,
    image: blogImage,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    catagory: "Guide",
    postedBy: "usha",
    date: "09/04/2025",
  },
  {
    id: 20,
    image: blogImage,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    catagory: "Guide",
    postedBy: "faisal",
    date: "01/06/2023",
  },
  {
    id: 21,
    image: blogImage,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    catagory: "Guide",
    postedBy: "bilal",
    date: "07/01/2023",
  },
  {
    id: 22,
    image: blogImage,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    catagory: "Guide",
    postedBy: "danish",
    date: "06/01/2025",
  },
  {
    id: 23,
    image: blogImage,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    catagory: "Guide",
    postedBy: "ghulam",
    date: "01/06/2025",
  },
  {
    id: 24,
    image: blogImage,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    catagory: "Guide",
    postedBy: "lamia",
    date: "05/01/2025",
  },
  {
    id: 25,
    image: blogImage,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    catagory: "Guide",
    postedBy: "rahul",
    date: "01/03/2025",
  },
  {
    id: 26,
    image: blogImage,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    catagory: "Guide",
    postedBy: "umer",
    date: "01/01/2025",
  },
  {
    id: 27,
    image: blogImage,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    catagory: "Guide",
    postedBy: "ohee",
    date: "11/08/2025",
  },
  {
    id: 28,
    image: blogImage,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    catagory: "Guide",
    postedBy: "rahul",
    date: "01/01/2025",
  },
  {
    id: 29,
    image: blogImage,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    catagory: "Guide",
    postedBy: "rafi",
    date: "08/03/2025",
  },
  {
    id: 30,
    image: blogImage,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    catagory: "Guide",
    postedBy: "niama",
    date: "01/01/2025",
  },
  {
    id: 31,
    image: blogImage,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    catagory: "Guide",
    postedBy: "niama",
    date: "01/01/2025",
  },
];
